# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6-rc.3
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from payrisk_base_server.apis.payrisk_api import router as PayriskApiRouter

# Configure logging for main
logger = logging.getLogger("alogram.payrisk.emulator")


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("🚀 Alogram PayRisk Emulator starting up...")
    logger.info("📍 API v0.1.6 Stable | Ready for integration testing.")
    yield
    logger.info("🛑 Alogram PayRisk Emulator shutting down...")


app = FastAPI(
    title="Payments Risk API",
    description="API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (&#x60;/risk/check&#x60;), with future account/session and KYC checks stubbed below. ",
    version="0.1.6",
    lifespan=lifespan,
)

app.include_router(PayriskApiRouter)
