# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.2.21
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
import sys
from inspect import getfullargspec
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Union

from payrisk_base_server.models.bank_transfer import BankTransfer
from payrisk_base_server.models.card import Card
from payrisk_base_server.models.crypto import Crypto
from payrisk_base_server.models.invoice import Invoice
from payrisk_base_server.models.realtime import Realtime
from payrisk_base_server.models.wallet import Wallet
from pydantic import (BaseModel, ConfigDict, Field, StrictStr, ValidationError,
                      field_validator)
from typing_extensions import Literal

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

PAYMENTMETHOD_ONE_OF_SCHEMAS = [
    "BankTransfer",
    "Card",
    "Crypto",
    "Invoice",
    "Realtime",
    "Wallet",
]


class PaymentMethod(BaseModel):
    """
    Union of instrument-specific payment details.
    """

    # data type: Card
    oneof_schema_1_validator: Optional[Card] = None
    # data type: Wallet
    oneof_schema_2_validator: Optional[Wallet] = None
    # data type: Realtime
    oneof_schema_3_validator: Optional[Realtime] = None
    # data type: BankTransfer
    oneof_schema_4_validator: Optional[BankTransfer] = None
    # data type: Crypto
    oneof_schema_5_validator: Optional[Crypto] = None
    # data type: Invoice
    oneof_schema_6_validator: Optional[Invoice] = None
    actual_instance: Optional[
        Union[BankTransfer, Card, Crypto, Invoice, Realtime, Wallet]
    ] = None
    one_of_schemas: List[str] = [
        "BankTransfer",
        "Card",
        "Crypto",
        "Invoice",
        "Realtime",
        "Wallet",
    ]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    discriminator_value_class_map: Dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = PaymentMethod.model_construct()
        error_messages = []
        match = 0
        # validate data type: Card
        if not isinstance(v, Card):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Card`")
        else:
            match += 1
        # validate data type: Wallet
        if not isinstance(v, Wallet):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Wallet`")
        else:
            match += 1
        # validate data type: Realtime
        if not isinstance(v, Realtime):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Realtime`")
        else:
            match += 1
        # validate data type: BankTransfer
        if not isinstance(v, BankTransfer):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `BankTransfer`"
            )
        else:
            match += 1
        # validate data type: Crypto
        if not isinstance(v, Crypto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Crypto`")
        else:
            match += 1
        # validate data type: Invoice
        if not isinstance(v, Invoice):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Invoice`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in PaymentMethod with oneOf schemas: BankTransfer, Card, Crypto, Invoice, Realtime, Wallet. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in PaymentMethod with oneOf schemas: BankTransfer, Card, Crypto, Invoice, Realtime, Wallet. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into Card
        try:
            instance.actual_instance = Card.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Wallet
        try:
            instance.actual_instance = Wallet.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Realtime
        try:
            instance.actual_instance = Realtime.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BankTransfer
        try:
            instance.actual_instance = BankTransfer.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Crypto
        try:
            instance.actual_instance = Crypto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Invoice
        try:
            instance.actual_instance = Invoice.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into PaymentMethod with oneOf schemas: BankTransfer, Card, Crypto, Invoice, Realtime, Wallet. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into PaymentMethod with oneOf schemas: BankTransfer, Card, Crypto, Invoice, Realtime, Wallet. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
